packages:
  - apps/web
  - apps/admin
  - packages/*

catalogMode: strict

catalog:
  '@eslint/js': ^10.0.1
  '@types/node': ^24.13.3
  '@vee-validate/zod': ^4.15.1
  '@vitejs/plugin-vue': ^6.0.8
  '@vue/eslint-config-prettier': ^10.2.0
  '@vue/eslint-config-typescript': ^14.9.0
  '@vue/tsconfig': ^0.9.1
  eslint: ^10.8.1
  eslint-import-resolver-typescript: ^4.4.5
  eslint-plugin-boundaries: ^7.2.0
  eslint-plugin-vue: ^10.10.0
  globals: ^17.11.0
  jiti: ^2.7.0
  openapi-typescript: ^7.13.0
  prettier: ^3.9.6
  typescript: ~6.0.2
  vee-validate: ^4.15.1
  vite: ^8.2.0
  vue: ^3.5.40
  vue-router: ^5.2.0
  vue-tsc: ^3.3.8
  zod: ^4.4.3

allowBuilds:
  esbuild: true
  unrs-resolver: true
